<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Parent Portal Credentials — {{ $className }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #111; }
        .school-name { font-size: 15px; font-weight: bold; text-align: center; }
        .doc-title { font-size: 13px; font-weight: bold; text-align: center; margin: 4px 0 2px; color: #1d4ed8; }
        .doc-meta { text-align: center; font-size: 10px; color: #555; margin-bottom: 14px; }
        .notice { background: #fef9c3; border: 1px solid #fde047; border-radius: 4px; padding: 8px 12px; margin-bottom: 14px; font-size: 10px; color: #713f12; }
        table { width: 100%; border-collapse: collapse; margin-top: 4px; }
        th { background: #1d4ed8; color: #fff; padding: 7px 8px; text-align: left; font-size: 10px; font-weight: bold; }
        td { border-bottom: 1px solid #e5e7eb; padding: 7px 8px; font-size: 11px; vertical-align: middle; }
        tr:nth-child(even) td { background: #f8fafc; }
        .mono { font-family: DejaVu Sans Mono, monospace; font-size: 10px; color: #1d4ed8; }
        .pwd { font-family: DejaVu Sans Mono, monospace; font-size: 10px; background: #fef2f2; color: #991b1b; border-radius: 3px; padding: 1px 4px; }
        .footer { margin-top: 18px; font-size: 9px; color: #888; text-align: center; border-top: 1px solid #e5e7eb; padding-top: 6px; }
        .num { text-align: center; color: #888; font-size: 10px; }
        .hint { font-size: 9px; color: #555; }
    </style>
</head>
<body>
    @include('components.pdf-header', ['school' => $school ?? null])

    <div class="doc-title">Parent Portal Login Credentials</div>
    <div class="doc-meta">
        Class: <strong>{{ $className }}</strong> &nbsp;|&nbsp;
        Generated: {{ now()->format('d M Y, H:i') }} &nbsp;|&nbsp;
        Total: {{ count($credentials) }} student(s)
    </div>

    <div class="notice">
        <strong>Confidential — share privately with each parent.</strong>
        Passwords shown here are temporary. Parents should log in and change them.
        This document was generated once — passwords cannot be retrieved again.
    </div>

    <table>
        <thead>
            <tr>
                <th class="num">#</th>
                <th style="width:26%;">Student Name</th>
                <th style="width:18%;">Class</th>
                <th style="width:32%;">Login Email</th>
                <th style="width:16%;">Temp Password</th>
            </tr>
        </thead>
        <tbody>
            @foreach($credentials as $i => $c)
            <tr>
                <td class="num">{{ $i + 1 }}</td>
                <td>{{ $c['name'] }}</td>
                <td>{{ $c['class_name'] }}</td>
                <td>
                    @if(!empty($c['portal_email']))
                        <span class="mono">{{ $c['portal_email'] }}</span>
                    @else
                        <span class="hint">No domain set — email not generated</span>
                    @endif
                </td>
                <td><span class="pwd">{{ $c['temp_password'] }}</span></td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Darasa Finance System &nbsp;|&nbsp; {{ now()->format('l, F j, Y \a\t g:i A') }}<br>
        For support, contact the school office.
    </div>
</body>
</html>
